Staff CRUD Added with Pagination,Sorting,Searching and Filter
HealthiPeoples/VRMicroservices pull request #6
Opened 2022-12-27 10:06 UTC by aakash-virtoustack

2022-12-27 11:03 UTC, ArunNKutty requested changes

2022-12-27 11:31 UTC, aakash-virtoustack commented on pkg/types/types.go
> +package types
Changed the file name

2022-12-27 11:52 UTC, aakash-virtoustack commented on vr-erp/controllers/staff_controller.go
> +func GetFilters(c *fiber.Ctx) types.Filters {
Yes @ArunNKutty  we are going to reuse the same fuction for all other get API's. And as you said we shifted the **GetFilters()** in to finlters.go file and renamed it as **ApplyFilters()**. 

But there in the object of filters we have a key known as filter

```
type Filters struct {
	**Filter     Filter**          // This will required separate key based on usecase
	Pagination Pagination
	Sort       Sort
	Search     Search
}
```

And for this reason we need to addon the result of **ApplyFilters()**.  in controller that will be in your observation on new commit. Please keep it as it's its required separately in our usecase.

2022-12-27 12:57 UTC, aakash-virtoustack commented on pkg/utils/utils.go
> +type CognitoClient struct {
Fixed the changes, got the logic to reuse the cognito client from aws.go file. For that, I have made small change in aws.go file. Please take a look into it!

2022-12-27 15:35 UTC, ArunNKutty requested changes

2022-12-27 15:35 UTC, ArunNKutty commented on pkg/utils/utils.go
> +func GetTenantDetails(c *fiber.Ctx) (string, error) {
Since this is a function which is handled during request processing , create a class called as requestmanager.go and put this function there

2022-12-28 05:27 UTC, aakash-virtoustack commented on pkg/filters/filters.go
> +func ApplyFilters(c *fiber.Ctx, mapping map[string]string) Filters {
Done.

**Note :**  We renamed the **Filters** with **APIFilters** so don't be get confuse

Please let me know anything else is in there which am forgetting to change

2022-12-28 05:35 UTC, ArunNKutty requested changes

2022-12-28 07:36 UTC, aakash-virtoustack commented on pkg/utils/utils.go
> +func GetTenantDetails(c *fiber.Ctx) (string, error) {
Done

2022-12-28 09:18 UTC, ArunNKutty approved these changes

2022-12-28 09:18 UTC, merged